### ISSUE TITLE
Minor bugs.

### ISSUE THREAD

**Issue by tibtiby** [Kinglilrowrow/PopcornTimeTV#2]
I’m farelly new to GitHub so I don’t know if it’s ok for me to post this here. First I wanna thank you for listening and for setting up a “how to” guide on how to install this app. It’s been hugelly helpfull. Now, after a few hours zapping through the app, I’ve noticed some bugs that weren’t there before:
1. After I select a Movie/Tv show, the loading screen with the title has a couple of black bars on the top and bottom of the screen.
2. When I press Menu from any screen, the list of content changes from full-screen to something similar to the iPhone vertical scrolling screen. Everything is crammed in the middle of the screen.
3. The search menu doesn’t work. No matter what I write, it says “we didn’t turn anything for...try something else.” Doesn’t work with either actors or movie titles.
4. The Watchlist menu has a hickup everytime i zap past it. Every other menu is fluid, but when I scroll through the top bar, there’s a 3-4 second waiting for the Watchlist tab. 
5. Something I’ve experienced with previous builds...everytime I select a Tv Show, and I start the episode...7-10 seconds in it just freezes. The bar is still buffering, but no matter how far it goes the content isn’t playing. I gotta hit menu, select play again and 3/4 times that does the trick.

That’s about all the glitches I’ve experienced so far. Thank you again for all the effort you’re putting in this and for keeping this app alive. Looking forward to 4k content. All the best.

**Comment by Kinglilrowrow** [comment]
1) Known issue and will be fixed in 4.2.1

2) Related to (1) and will be fixed in 4.2.1 also

3) It searches for TV shows only, what you are searching for needs to be spelt 100% correctly and wait 25secs for the view controller to update whats on screen. (this will be improved upon in future updates)

4) Have not noticed this one, I'll look into that

5) Yeah, this is a VLCKit issue and unrelated to PopcornTimeTV itself sadly, the media player thats default on tvOS doesn't support what we need so are forced to use VLCKit, its still under heavy development itself so we will have to wait a while before this one is fixed sadly.

You did post in the right place as well by the way. 

Thanks.

**Comment by tibtiby** [comment]
Also, is there any chance for a “insert/choose your own subtitle site/version” feature?

**Comment by tibtiby** [comment]
There’s one more bug I’ve encountered. 
6. I can only pause the movie/tv show only once during playback. If i try and pause it again at a later time, nothing happens. I have to force close the app and restart it, select the contect again and resume playing. Never happened before. :)

**Comment by Kinglilrowrow** [comment]
Possible to add the subtitles feature but not something i'd rush into doing anytime soon. 

As for the other issue you reported, I can't seem to reproduce it on tvOS 11.1 (Apple TV 4K). 

What tvOS version are you using and what Apple TV do you own? (I take it 4K as well from your previous comment)

**Comment by tibtiby** [comment]
Apple TV 4 - 32gb, tvos 11.1

**Comment by Kinglilrowrow** [comment]
Okay i'll look into these and hope to get them all squashed with the 4.2.1 release when it is ready. 

Thanks.
